server:
  port: 9093
spring:
  application:
    name: FOODCATELOG-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/foodItems
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
management:
  server:
    port: 9001
    address: 127.0.0.1
  endpoints:
    enabled-by-default: true
    info:
      enabled: true
    shutdown:
      enabled: true
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      